### ISSUE TITLE
Commodities in different forms

### ISSUE THREAD

**Issue by BardenB** [amoralesch/hledger-db-grafana#19]
I haven't taken a deep look into the code, but how hard would it be to change the commodity format to, say, `$##,###.##` rather than having USD at the end? I have years and years of data in using the `$` for USD, and I'm not sure how to easily switch all of it to the format required.

**Comment by amoralesch** [comment]
Hi @BardenB, thanks for checking the repo!

From the top of my head, I think there are only 2 places where the format of the commodity matters: `fx_rates.split_price()` and `hledger.current_commodites()`. Let me have a quick test locally and I'll report back.

**Comment by amoralesch** [comment]
I created a very, very small example using `$ #,###.##` syntax, and I run it with the code in branch `issue/19`, it seems to be working.

The change is located in the 2 places I mentioned before, `fx_rates.py` to load the exchange rates, and in `hledger.py` to find out which commodities are currently in use.

Would you mind trying the code and see if it works for you too?

**Comment by amoralesch** [comment]
Oh, I didn't read your message carefully enough. Do you have your format like `$#,###.##`? i.e., no space between the symbol and the number? Let me know if that is the case. The change I did in this branch only works when there is a space between the symbol and the amount.

**Comment by BardenB** [comment]
Correct, I use no space between `$` and the value. However, i also wrote a quick regex script to convert all `$#,###.##` to `#,###.## USD` while I was doing testing. I can share that soon if it helps.

**Comment by amoralesch** [comment]
Sure, it can help, we can add it to the repo with a note about how to use it. Maybe others will find it useful too!
